download:
	nbc -d -S=usb bigMission.nxc sensor.nxc move.nxc claw.nxc
	nbc -d -S=usb petsMission.nxc sensor.nxc move.nxc claw.nxc
	nbc -d -S=usb treeMission.nxc sensor.nxc move.nxc claw.nxc

compile:
	nbc -O=frame bigMission.nxc sensor.nxc move.nxc claw.nxc
	nbc -O=frame petsMission.nxc sensor.nxc move.nxc claw.nxc
	nbc -O=frame treeMission.nxc sensor.nxc move.nxc claw.nxc
